# vim:ft=kitty

## name:       Gruvbox Material Dark Hard
## author:     sainnhe
## license:    MIT
## upstream:   :contentReference[oaicite:0]{index=0}
## blurb:      Gruvbox with Material Palette (dark hard variant)


include ~/.config/themes/tokyo-night/kitty/colors.conf


